### ISSUE TITLE
Add the NPC's text to the dialog box

### ISSUE THREAD

**Issue by Poli93** [mrthinger/wow-voiceover#61] opened 2023-04-12 19:26 UTC
It'd be nice for those of us with ADHD who forget what the NPC says to be able to see it and read it whilst the voiceover reads it back to us!

**Comment by mrthinger** [comment] 2023-12-09 21:30
This is a huge thing to take on and do correctly. It would add value, but we dont have the bandwidth to take it on anytime soon.

There was some talk a while back in the discord about generating offsets of the spoken text from the audio files using that to sync to the shown text. The small addon window that shows can't fit the entire quest into it at the same time. If you're looking to see the static text in its entirety, you could open the quest log and follow it yourself.

**Comment by mrthinger** [comment] 2023-12-09 23:17
closing as duplicate of #44

**Closed by mrthinger** 2023-12-09 23:17 UTC
Labels: enhancement
